---
# Thycotic Secret Server integration gh action
name: 'Thycotic SS integration'
description: 'Secret management using Thycotic SS API'
inputs:
  url:
    description: The url of the secret server
    required: true
  username:
    description: Username for authenticating to the secret server
    required: true
  password:
    description: Password for authenticating to the secret server
    required: true
  get-secret-1:
    description: "Secret in the format <SECRET_ID>/<SECRET_FIELD>"
    required: false
    default: ""
  get-secret-2:
    description: "Secret in the format <SECRET_ID>/<SECRET_FIELD>"
    required: false
    default: ""
  get-secret-3:
    description: "Secret in the format <SECRET_ID>/<SECRET_FIELD>"
    required: false
    default: ""
  get-secret-4:
    description: "Secret in the format <SECRET_ID>/<SECRET_FIELD>"
    required: false
    default: ""
  get-secret-5:
    description: "Secret in the format <SECRET_ID>/<SECRET_FIELD>"
    required: false
    default: ""
  get-secret-6:
    description: "Secret in the format <SECRET_ID>/<SECRET_FIELD>"
    required: false
    default: ""
  get-secret-7:
    description: "Secret in the format <SECRET_ID>/<SECRET_FIELD>"
    required: false
    default: ""
  get-secret-8:
    description: "Secret in the format <SECRET_ID>/<SECRET_FIELD>"
    required: false
    default: ""
outputs:
  secret-1:
    description: Retrieved secret value
  secret-2:
    description: Retrieved secret value
  secret-3:
    description: Retrieved secret value
  secret-4:
    description: Retrieved secret value
  secret-5:
    description: Retrieved secret value
  secret-6:
    description: Retrieved secret value
  secret-7:
    description: Retrieved secret value
  secret-8:
    description: Retrieved secret value
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.url }}
    - ${{ inputs.username }}
    - ${{ inputs.password }}
    - ${{ inputs.get-secret-1 }}
    - ${{ inputs.get-secret-2 }}
    - ${{ inputs.get-secret-3 }}
    - ${{ inputs.get-secret-4 }}
    - ${{ inputs.get-secret-5 }}
    - ${{ inputs.get-secret-6 }}
    - ${{ inputs.get-secret-7 }}
    - ${{ inputs.get-secret-8 }}
