---
# Thycotic Secret Server integration gh action
name: 'Thycotic SS integration'
description: 'Secret management using Thycotic SS API'
inputs:
  url:
    description: The url of the secret server
    required: true
  username:
    description: Username for authenticating to the secret server
    required: true
  password:
    description: Password for authenticating to the secret server
    required: true
  get_secret_1:
    description: "Secret in the format <SECRET_ID>/<SECRET_FIELD>"
    required: false
    default: ""
  get_secret_2:
    description: "Secret in the format <SECRET_ID>/<SECRET_FIELD>"
    required: false
    default: ""
  get_secret_3:
    description: "Secret in the format <SECRET_ID>/<SECRET_FIELD>"
    required: false
    default: ""
  get_secret_4:
    description: "Secret in the format <SECRET_ID>/<SECRET_FIELD>"
    required: false
    default: ""
  get_secret_5:
    description: "Secret in the format <SECRET_ID>/<SECRET_FIELD>"
    required: false
    default: ""
  get_secret_6:
    description: "Secret in the format <SECRET_ID>/<SECRET_FIELD>"
    required: false
    default: ""
  get_secret_7:
    description: "Secret in the format <SECRET_ID>/<SECRET_FIELD>"
    required: false
    default: ""
  get_secret_8:
    description: "Secret in the format <SECRET_ID>/<SECRET_FIELD>"
    required: false
    default: ""
runs:
  outputs:
    secret_1:
      description: Retrieved secret value
    secret_2:
      description: Retrieved secret value
    secret_3:
      description: Retrieved secret value
    secret_4:
      description: Retrieved secret value
    secret_5:
      description: Retrieved secret value
    secret_6:
      description: Retrieved secret value
    secret_7:
      description: Retrieved secret value
    secret_8:
      description: Retrieved secret value
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.url }}
    - ${{ inputs.username }}
    - ${{ inputs.password }}
    - ${{ inputs.get_secret_1 }}
    - ${{ inputs.get_secret_2 }}
    - ${{ inputs.get_secret_3 }}
    - ${{ inputs.get_secret_4 }}
    - ${{ inputs.get_secret_5 }}
    - ${{ inputs.get_secret_6 }}
    - ${{ inputs.get_secret_7 }}
    - ${{ inputs.get_secret_8 }}
